### ISSUE TITLE
Deepspeed zero2加了offload就报错

### ISSUE THREAD

**Issue by JohnZhuYX** [QwenLM/Qwen-7B#113]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

[INFO|trainer.py:1681] 2023-08-08 10:27:09,822 >> ***** Running training *****
[INFO|trainer.py:1682] 2023-08-08 10:27:09,822 >>   Num examples = 272,514
[INFO|trainer.py:1683] 2023-08-08 10:27:09,822 >>   Num Epochs = 1
[INFO|trainer.py:1684] 2023-08-08 10:27:09,822 >>   Instantaneous batch size per device = 1
[INFO|trainer.py:1687] 2023-08-08 10:27:09,822 >>   Total train batch size (w. parallel, distributed & accumulation) = 512
[INFO|trainer.py:1688] 2023-08-08 10:27:09,822 >>   Gradient Accumulation steps = 512
[INFO|trainer.py:1689] 2023-08-08 10:27:09,822 >>   Total optimization steps = 532
[INFO|trainer.py:1690] 2023-08-08 10:27:09,824 >>   Number of trainable parameters = 286,261,248
  0%|                                                                                                                                                                                   | 0/532 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/johnzyx/working/pythonprojects/LLaMA-Efficient-Tuning/src/train_bash.py", line 14, in <module>
    main()
  File "/home/johnzyx/working/pythonprojects/LLaMA-Efficient-Tuning/src/train_bash.py", line 5, in main
    run_exp()
  File "/home/johnzyx/working/pythonprojects/LLaMA-Efficient-Tuning/src/llmtuner/tuner/tune.py", line 19, in run_exp
    run_pt(model_args, data_args, training_args, finetuning_args, callbacks)
  File "/home/johnzyx/working/pythonprojects/LLaMA-Efficient-Tuning/src/llmtuner/tuner/pt/workflow.py", line 46, in run_pt
    train_result = trainer.train()
  File "/home/johnzyx/environment/anaconda-env/python3.10/lib/python3.10/site-packages/transformers/trainer.py", line 1531, in train
    return inner_training_loop(
  File "/home/johnzyx/environment/anaconda-env/python3.10/lib/python3.10/site-packages/transformers/trainer.py", line 1804, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/johnzyx/environment/anaconda-env/python3.10/lib/python3.10/site-packages/transformers/trainer.py", line 2657, in training_step
    self.accelerator.backward(loss)
  File "/home/johnzyx/environment/anaconda-env/python3.10/lib/python3.10/site-packages/accelerate/accelerator.py", line 1847, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/home/johnzyx/environment/anaconda-env/python3.10/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 167, in backward
    self.engine.backward(loss, **kwargs)
  File "/home/johnzyx/environment/githubtool/DeepSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/johnzyx/environment/githubtool/DeepSpeed/deepspeed/runtime/engine.py", line 1896, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/home/johnzyx/environment/githubtool/DeepSpeed/deepspeed/runtime/zero/stage_1_and_2.py", line 1960, in backward
    self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
  File "/home/johnzyx/environment/githubtool/DeepSpeed/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
    scaled_loss.backward(retain_graph=retain_graph)
  File "/home/johnzyx/environment/anaconda-env/python3.10/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/johnzyx/environment/anaconda-env/python3.10/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/johnzyx/environment/anaconda-env/python3.10/lib/python3.10/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/johnzyx/environment/anaconda-env/python3.10/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 157, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/home/johnzyx/environment/anaconda-env/python3.10/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/johnzyx/environment/githubtool/DeepSpeed/deepspeed/runtime/zero/stage_1_and_2.py", line 856, in reduce_partition_and_remove_grads
    self.reduce_ready_partitions_and_remove_grads(param, i)
  File "/home/johnzyx/environment/githubtool/DeepSpeed/deepspeed/runtime/zero/stage_1_and_2.py", line 1314, in reduce_ready_partitions_and_remove_grads
    self.reduce_independent_p_g_buckets_and_remove_grads(param, i)
  File "/home/johnzyx/environment/githubtool/DeepSpeed/deepspeed/runtime/zero/stage_1_and_2.py", line 884, in reduce_independent_p_g_buckets_and_remove_grads
    self.reduce_ipg_grads()
  File "/home/johnzyx/environment/githubtool/DeepSpeed/deepspeed/runtime/zero/stage_1_and_2.py", line 1301, in reduce_ipg_grads
    self.copy_grads_in_partition(param)
  File "/home/johnzyx/environment/githubtool/DeepSpeed/deepspeed/runtime/zero/stage_1_and_2.py", line 1222, in copy_grads_in_partition
    self.async_accumulate_grad_in_cpu_via_gpu(param)
  File "/home/johnzyx/environment/githubtool/DeepSpeed/deepspeed/runtime/zero/stage_1_and_2.py", line 1126, in async_accumulate_grad_in_cpu_via_gpu
    accumulate_gradients()
  File "/home/johnzyx/environment/githubtool/DeepSpeed/deepspeed/runtime/zero/stage_1_and_2.py", line 1105, in accumulate_gradients
    param.grad_accum.data.view(-1).add_(dest_buffer)
AttributeError: 'NoneType' object has no attribute 'data'
  0%|                                                                                                                                                                                   | 0/532 [00:00<?, ?it/s]
[2023-08-08 10:27:11,312] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 8706
[2023-08-08 10:27:11,312] [ERROR] [launch.py:321:sigkill_handler] ['/home/johnzyx/environment/anaconda-env/python3.10/bin/python', '-u', 'src/train_bash.py', '--local_rank=0', '--deepspeed', 'src/deepspeedZero2.json', '--stage', 'pt', '--model_name_or_path', '/home/johnzyx/working/AI/model/Qwen-7B', '--do_train', '--dataset', 'wikipedia_zh_zyx', '--template', 'chatml', '--finetuning_type', 'lora', '--lora_target', 'c_attn,c_proj,w1,w2', '--lora_rank', '128', '--output_dir', '/media/johnzyx/本地磁盘/working/AI/outputmodel/QWen7B-sft-lora', '--per_device_train_batch_size', '1', '--gradient_accumulation_steps', '512', '_scheduler_type', 'constant_with_warmup', '--logging_steps', '1', '--save_steps', '1000', '--learning_rate', '5e-5', '--num_train_epochs', '1.0', '--ddp_find_unused_parameters', 'False', '--plot_loss', '--fp16', 'false', '--bf16', 'true'] exits with return code = 1

### 复现方法 | Steps To Reproduce

{
  "fp16": {
    "enabled": "auto",
    "loss_scale": 0,
    "loss_scale_window": 1000,
    "initial_scale_power": 16,
    "hysteresis": 2,
    "min_loss_scale": 1
  },

  "optimizer": {
    "type": "AdamW",
    "params": {
      "lr": "auto",
      "betas": "auto",
      "eps": "auto",
      "weight_decay": "auto"
    }
  },

  "scheduler": {
    "type": "WarmupLR",
    "params": {
      "warmup_min_lr": "auto",
      "warmup_max_lr": "auto",
      "warmup_num_steps": "auto"
    }
  },

  "zero_optimization": {
    "stage": 2,
    "offload_optimizer": {
      "device": "cpu",
      "pin_memory": true
    },
    "offload_param": {
      "device": "cpu",
      "pin_memory": true
    },
    "overlap_comm": true,
    "contiguous_gradients": true,
    "sub_group_size": 1e9,
    "reduce_scatter": true,
    "reduce_bucket_size": "auto",
    "zero_quantized_weights": false,
    "zero_hpz_partition_size": 16,
    "zero_quantized_gradients": false
  },
  "gradient_accumulation_steps": 512,
  "gradient_clipping": "auto",
  "steps_per_print": 2000,
  "train_batch_size": 512,
  "train_micro_batch_size_per_gpu": 1,
  "wall_clock_breakdown": false
}
deepspeed 去掉

 "offload_optimizer": {
      "device": "cpu",
      "pin_memory": true
    },
    "offload_param": {
      "device": "cpu",
      "pin_memory": true
    },
能正常运行，但是过会就OOM，加上这个offload直接报上面的错误

### 运行环境 | Environment

```Markdown
- OS Ubuntu 23:
- Python 3.10:
- Transformers :4.32.0
- PyTorch 2.0.1:
- CUDA 12.1:
```

**Comment by fyabc** [comment]
@JohnZhuYX 您好，请问这个问题在最新代码上解决了吗？
