### ISSUE TITLE
TypeError: new_empty(): argument 'size' must be tuple of ints, but found element of type float at pos 2049[BUG] <title>

### ISSUE THREAD

**Issue by Denilah** [QwenLM/Qwen-7B#122]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

使用了deepspeed zero_optimization stage 3.

Traceback (most recent call last):
  File "/gemini/code/new/src/sft_train.py", line 535, in <module>
    main()
  File "/gemini/code/new/src/sft_train.py", line 260, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 488, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2700, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 434, in wrapper
    f(module, *args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/pretrain/modeling_qwen.py", line 850, in __init__
    self.transformer = QWenModel(config)
  File "/root/miniconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 434, in wrapper
    f(module, *args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/pretrain/modeling_qwen.py", line 623, in __init__
    [
  File "/root/.cache/huggingface/modules/transformers_modules/pretrain/modeling_qwen.py", line 624, in <listcomp>
    QWenBlock(
  File "/root/miniconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 434, in wrapper
    f(module, *args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/pretrain/modeling_qwen.py", line 502, in __init__
    self.attn = QWenAttention(config, layer_number=layer_idx)
  File "/root/miniconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 434, in wrapper
    f(module, *args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/pretrain/modeling_qwen.py", line 248, in __init__
    self.logn_tensor = torch.Tensor(logn_list)[None, :, None, None]
  File "/root/miniconda3/lib/python3.9/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 246, in new_tensor
    tensor = _orig_torch_empty(0, device=device).new_empty(*args)
TypeError: new_empty(): argument 'size' must be tuple of ints, but found element of type float at pos 2049

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 20.04.5
- Python:3.9.17
- Transformers:4.31.0
- PyTorch:2.0.1
- CUDA:11.7
```

**Comment by JunityZhan** [comment]
https://github.com/QwenLM/Qwen-7B/issues/106#issuecomment-1668836524
