### ISSUE TITLE
[BUG] <title>ModuleNotFoundError: No module named 'transformers_modules.Qwen'

### ISSUE THREAD

**Issue by zhangziliang04** [QwenLM/Qwen-7B#140]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

(base) (venv) PS D:\work\chatgpt\cots\qwenlm\Qwen-7B> python web_demo.py                   
Call args:['web_demo.py']
Args:Namespace(share=False, inbrowser=False, server_port=80, server_name='0.0.0.0', exit=False, model_revision='')
Traceback (most recent call last):
  File "D:\work\chatgpt\cots\qwenlm\Qwen-7B\web_demo.py", line 22, in <module>
    tokenizer = AutoTokenizer.from_pretrained(
  File "D:\work\chatgpt\cots\qwenlm\Qwen-7B\venv\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 685, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "D:\work\chatgpt\cots\qwenlm\Qwen-7B\venv\lib\site-packages\transformers\dynamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "D:\work\chatgpt\cots\qwenlm\Qwen-7B\venv\lib\site-packages\transformers\dynamic_module_utils.py", line 164, in get_class_in_module
    module = importlib.import_module(module_path)
  File "D:\tools\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.Qwen'
(base) (venv) PS D:\work\chatgpt\cots\qwenlm\Qwen-7B> 

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jiacheo** [comment]
我运行cli_demo.py也会出现类似的错误，运行web_demo.py则没问题。
同样是Windows环境

**Comment by alanlaye617** [comment]
我之前运行cli_demo.py也遇到同样的错误。之后把 DEFAULT_CKPT_PATH = 'QWen/QWen-7B-Chat' 改成了 'Qwen/Qwen-7B-Chat' 就一切正常了

**Comment by alixiaodi** [comment]
我的也是同样问题，下载源码后，安装了依赖，启动任何demo都是这个错误

**Comment by alixiaodi** [comment]
python版本3.10.4

**Comment by linuaries** [comment]
感觉是起名问题，在ModelScope上都是qwen/Qwen-7B-Chat这类第一个字母小写的。到了HuggingFace上就是首字母大写。。。

**Comment by starstardd** [comment]
把 DEFAULT_CKPT_PATH = 'QWen/QWen-7B-Chat' 改成了 'Qwen/Qwen-7B-Chat/' 就一切正常了
