### ISSUE TITLE
[BUG] AttributeError: 'QWenLMHeadModel' object has no attribute 'chat_stream'

### ISSUE THREAD

**Issue by p-moon** [QwenLM/Qwen-7B#142]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

(Qwen-7B) ☁  Qwen-7B [main] ⚡  python web_demo.py
Call args:['web_demo.py']
Args:Namespace(share=False, inbrowser=False, server_port=7860, server_name='0.0.0.0', exit=False, model_revision='')
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get better performance https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get better performance https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention https://github.com/Dao-AILab/flash-attention
/home/moon/develop/chatglm/Qwen-7B/web_demo.py:153: GradioUnusedKwargWarning: You have unused kwarg parameters in Chatbot, please remove them: {'lines': 10}
  chatbot = gr.Chatbot(lines=10, label='Qwen-7B-Chat', elem_classes="control-height")
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
User: 是是是
Traceback (most recent call last):
  File "/home/moon/.conda/envs/Qwen-7B/lib/python3.10/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/moon/.conda/envs/Qwen-7B/lib/python3.10/site-packages/gradio/blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "/home/moon/.conda/envs/Qwen-7B/lib/python3.10/site-packages/gradio/blocks.py", line 1111, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/moon/.conda/envs/Qwen-7B/lib/python3.10/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/home/moon/.conda/envs/Qwen-7B/lib/python3.10/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/moon/.conda/envs/Qwen-7B/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/moon/.conda/envs/Qwen-7B/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/moon/.conda/envs/Qwen-7B/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/moon/.conda/envs/Qwen-7B/lib/python3.10/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/home/moon/.conda/envs/Qwen-7B/lib/python3.10/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/moon/develop/chatglm/Qwen-7B/web_demo.py", line 115, in predict
    for response in model.chat_stream(tokenizer, query, history=task_history):
  File "/home/moon/.conda/envs/Qwen-7B/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'QWenLMHeadModel' object has no attribute 'chat_stream'

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by JianxinMa** [comment]
您好，应该是代码版本问题。请重新拉取 huggingface 上的代码，比如重新执行下 from_pretrained("Qwen/Qwen-7B-Chat")

https://github.com/QwenLM/Qwen-7B/issues/119
