### ISSUE TITLE
when using cli_demo.py

### ISSUE THREAD

**Issue by yumingfan-0219** [QwenLM/Qwen-7B#168]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用/cli_demo.py得到如下输出
User: 123

Qwen-7B: [('123', "I'm sorry, but I don't understand what you are asking for. Could you please provide more information or clarify your question?")]
User> 456
Traceback (most recent call last):
  File "/work/home/project/Qwen-7B0811/cli_demo.py", line 192, in <module>
    main()
  File "/work/home/project/Qwen-7B0811/cli_demo.py", line 180, in main
    for response in model.chat(tokenizer, query, history=history):
  File "/root/.cache/huggingface/modules/transformers_modules/chat/modeling_qwen.py", line 970, in chat
    raw_text, context_tokens = make_context(
  File "/root/.cache/huggingface/modules/transformers_modules/chat/qwen_generation_utils.py", line 150, in make_context
    response_text, response_tokens_part = _tokenize_str(
  File "/root/.cache/huggingface/modules/transformers_modules/chat/qwen_generation_utils.py", line 139, in _tokenize_str
    ) + nl_tokens + tokenizer.encode(content, allowed_special=set())
  File "/work/home/env_try/anaconda3/envs/ctyun_llm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2348, in encode
    encoded_inputs = self.encode_plus(
  File "/work/home/env_try/anaconda3/envs/ctyun_llm/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2756, in encode_plus
    return self._encode_plus(
  File "/work/home/env_try/anaconda3/envs/ctyun_llm/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 649, in _encode_plus
    first_ids = get_input_ids(text)
  File "/work/home/env_try/anaconda3/envs/ctyun_llm/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 635, in get_input_ids
    raise ValueError(
ValueError: Input [('123', "I'm sorry, but I don't understand what you are asking for. Could you please provide more information or clarify your question?"), ('123', [...])] is not valid. Should be a string, a list/tuple of strings or a list/tuple of integers.

### 期望行为 | Expected Behavior

交互式输入输出能够得到正确返回

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by fyabc** [comment]
@yumingfan-0219 您好，观察到您的cli_demo.py还是调用的`model.chat()`接口，可以更新下最新代码再重试吗？（最新代码使用`model.chat_stream()`接口）

**Comment by yumingfan-0219** [comment]
您好，感谢回复
使用chat_stream时，提示QWen...不存在this attribute，暂不清楚这是否为代码版本原因？我使用的是最新版的代码

**Comment by fyabc** [comment]
> 您好，感谢回复 使用chat_stream时，提示QWen...不存在this attribute，暂不清楚这是否为代码版本原因？我使用的是最新版的代码

应该是HuggingFace上modeling_qwen.py等代码没有更新的原因，您是否是将模型下载到本地然后加载的？可以从HuggingFace上下载一下最新模型和相关代码，然后重试一下

**Comment by fyabc** [comment]
可以参考 #119
