### ISSUE TITLE
[BUG] <title>运用官方的readme里面的代码调用api还出错误openai.error.APIError: HTTP code 502 from API ()

### ISSUE THREAD

**Issue by ArtificialZeng** [QwenLM/Qwen-7B#198]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

openai.error.APIError: HTTP code 502 from API ()

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by yangapku** [comment]
您好，建议您详细填写下复现方法和运行环境信息，便于我们进行排查。另外也请您先参考下我们在issue #191中的环境配置，尤其是pydantic版本，可以尝试对齐下各个库的版本，再观察下问题是否仍然存在。

**Comment by ArtificialZeng** [comment]
> 您好，建议您详细填写下复现方法和运行环境信息，便于我们进行排查。另外也请您先参考下我们在issue #191中的环境配置，尤其是pydantic版本，可以尝试对齐下各个库的版本，再观察下问题是否仍然存在。

您的deepspeed版本是多少？？



CUDA_VISIBLE_DEVICES=1 python openai_v2.py -c /datas3/HFs/Qwen/Qwen-7B-Chat --server-port 8004 --server-name 172.16.8.194 >111.txt
/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/zengzijian/miniconda3/envs/test_qwen did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/pydantic/_internal/_config.py:269: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'validate_all' has been renamed to 'validate_default'
  warnings.warn(message, UserWarning)
/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/pydantic/_internal/_fields.py:127: UserWarning: Field "model_persistence_threshold" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1099, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers/generation/utils.py", line 27, in <module>
    from ..deepspeed import is_deepspeed_zero3_enabled
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers/deepspeed.py", line 37, in <module>
    from accelerate.utils.deepspeed import HfDeepSpeedConfig as DeepSpeedConfig
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 135, in <module>
    from .launch import (
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/accelerate/utils/launch.py", line 33, in <module>
    from ..utils.other import is_port_in_use, merge_dicts
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/accelerate/utils/other.py", line 31, in <module>
    from deepspeed import DeepSpeedEngine
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/__init__.py", line 16, in <module>
    from . import module_inject
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/module_inject/replace_module.py", line 792, in <module>
    from ..pipe import PipelineModule
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
    from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
    from .module import PipelineModule, LayerSpec, TiedLayerSpec
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 25, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/runtime/config.py", line 29, in <module>
    from .zero.config import get_zero_config, ZeroStageEnum
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/runtime/zero/__init__.py", line 6, in <module>
    from .partition_parameters import ZeroParamType
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 616, in <module>
    class Init(InsertPostInitMethodToModuleSubClasses):
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 618, in Init
    param_persistence_threshold = get_config_default(DeepSpeedZeroConfig, "param_persistence_threshold")
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/deepspeed/runtime/config_utils.py", line 116, in get_config_default
    field_name).required, f"'{field_name}' is a required field and does not have a default value"
AttributeError: 'FieldInfo' object has no attribute 'required'. Did you mean: 'is_required'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zengzijian/ai_code/Qwen-7B-main/openai_v2.py", line 214, in <module>
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 480, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 431, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 268, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 146, in check_imports
    importlib.import_module(imp)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers_stream_generator/__init__.py", line 1, in <module>
    from .main import init_stream_support
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers_stream_generator/main.py", line 1, in <module>
    from transformers import (
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1090, in __getattr__
    value = getattr(module, name)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1089, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1101, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.generation.utils because of the following error (look up to see its traceback):
'FieldInfo' object has no attribute 'required'

**Comment by yangapku** [comment]
您好，使用openai api功能不需要deepspeed，仅安装我们requirements.txt和readme对应部分中额外的几个库（fastapi uvicorn openai pydantic sse_starlette）即可。如果使用bnb量化，则再额外考虑安装上readme提到的bitsandbytes就ok。

**Comment by ArtificialZeng** [comment]
> 您好，使用openai api功能不需要deepspeed，目前我们的所有官方开源的功能依赖项中也没有deepspeed，运行推理仅安装我们requirements.txt，和readme对应部分中openai api相关额外的几个库（fastapi uvicorn openai pydantic sse_starlette）即可。如果使用bnb量化，则再额外考虑安装上readme提到的bitsandbytes就ok。

非常感谢您耐心的回复， 您的官方代码openai_api.py有bug，我已经修改好 提交了pr。能劳烦您审核一下吗？ 非常感谢您领导的千问项目！

**Comment by yangapku** [comment]
收到回复~ 想了解下您在使用时都是按照`stream=False`这样请求的吗？我们排查下问题哈。

**Comment by ArtificialZeng** [comment]
![image](https://github.com/QwenLM/Qwen-7B/assets/39647839/faf7e71d-f1cd-4a59-b2c7-b4ae1171b5a0)
您能不能看到图片，如果"stream":true, 是逐token蹦出来的。  只有加上我的代码，然后stream false才是完整的拼接好的答案。
我是用post请求测试的

{
  "model": "Qwen-7B-Chat",
  "messages": [
    {
      "role": "user",
      "content": "你叫什么名字？"
    }
  ],
  "temperature": 100,
  "top_p": 30,
  "n": 100,
  "max_tokens": 100,
  "stream": true
}

**Comment by yangapku** [comment]
恩恩是的，能看到图片哈。

关于您提到的请求时候`stream`这个参数，指的就是是否使用“流式输出”哈。在流式输出的情况下，结果就是逐token返回回来的，和我们通义千问网页版的呈现效果、以及chatgpt网页版的效果是一致的，也是现在比较流行的展示方式（降低用户等待首字结果出现的时间）。所以这个是符合预期的，我们提供的example默认也是打开了`stream=True`。如果您在客户端命令行中，执行我们readme的示例代码，也会观察到逐字生成的效果。

`stream=False`的情况，就是关闭流式输出，这时候结果预期中应该要一并返回回来。但是这里确实有一个如您所说的报错，我们会参考您的PR，看下如何解决掉哈，感谢您指出这个问题。

**Comment by ArtificialZeng** [comment]
> 恩恩是的，能看到图片哈。
> 
> 关于您提到的请求时候`stream`这个参数，指的就是是否使用“流式输出”哈。在流式输出的情况下，结果就是逐token返回回来的，和我们通义千问网页版的呈现效果、以及chatgpt网页版的效果是一致的，也是现在比较流行的展示方式（降低用户等待首字结果出现的时间）。所以这个是符合预期的，我们提供的example默认也是打开了`stream=True`。如果您在客户端命令行中，执行我们readme的示例代码，也会观察到逐字生成的效果。
> 
> `stream=False`的情况，就是关闭流式输出，这时候结果预期中应该要一并返回回来。但是这里确实有一个如您所说的报错，我们会参考您的PR，看下如何解决掉哈，感谢您指出这个问题。

非常感谢您耐心的回复， 我的所提交的pr只是把流式的结果拼接了。他是一个生成器。并且只有运行openai_api.py代码的时候，才会出现这个问题。请求时的方式不影响原代码。还是希望能贡献您这个伟大的项目。

非常喜欢你们的模型，并写了一个贵模型的微调教程：https://github.com/ArtificialZeng/Qwen-Tuning

**Comment by yangapku** [comment]
感谢您的支持！您的PR我们修改后已经合并哈，相关的几个issue我就关闭了。欢迎您提出更多建议！
