### ISSUE TITLE
[BUG] <title>运行openapi.py那个脚本报错ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by ArtificialZeng** [QwenLM/Qwen-7B#199]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

CUDA_VISIBLE_DEVICES=1 python openai_v2.py -c /datas3/HFs/Qwen/Qwen-7B-Chat --server-port 8004 --server-name 172.16.8.194 >111.txt
/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: /home/zengzijian/miniconda3/envs/test_qwen did not contain ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...
  warn(msg)
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:09<00:00,  1.14s/it]
INFO:     Started server process [1067205]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://172.16.8.194:8004 (Press CTRL+C to quit)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/fastapi/applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/zengzijian/miniconda3/envs/test_qwen/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/zengzijian/ai_code/Qwen-7B-main/openai_v2.py", line 126, in create_chat_completion
    response, _ = model.chat_stream(tokenizer, query, history=history)
ValueError: too many values to unpack (expected 2)

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by ArtificialZeng** [comment]
已解决，并提交pr ，https://github.com/QwenLM/Qwen-7B/pull/201
