### ISSUE TITLE
[BUG]在启动openai_api.py后报错'ChatCompletionResponse' object has no attribute 'model_dump_json'

### ISSUE THREAD

**Issue by qihangf** [QwenLM/Qwen-7B#229]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

python  openai_api.py  -c ./model

我启动这个，来使用langchain-chatchat项目

### 运行环境 | Environment

```Markdown
- OS:Ubuntu
- Python:3.9
- Transformers:4.31.0
- PyTorch:2.0.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

### 备注 | Anything else?

完整报错信息
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/data/software/anaconda3/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408,in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/data/software/anaconda3/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84,in __call__
    return await self.app(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/data/software/anaconda3/lib/python3.9/site-packages/sse_starlette/sse.py", line 251, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/data/software/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 574, in __aexit__
    raise exceptions[0]
  File "/data/software/anaconda3/lib/python3.9/site-packages/sse_starlette/sse.py", line 240, in wrap
    await func()
  File "/data/software/anaconda3/lib/python3.9/site-packages/sse_starlette/sse.py", line 225, in stream_response
    async for data in self.body_iterator:
  File "/home/wyxx/warBackup/ner/Qwen-7B/openai_api.py", line 145, in predict
    yield "{}".format(chunk.model_dump_json(exclude_unset=True))
AttributeError: 'ChatCompletionResponse' object has no attribute 'model_dump_json'

**Comment by RipperTs** [comment]
更新 `pydantic` 依赖版本，使用最新版 或许 `2.x`

**Comment by qihangf** [comment]
> 

更新之后，变成这样了
 File "/home/wyxx/warBackup/ner/Qwen-7B/openai_api.py", line 11, in <module>
    from fastapi import FastAPI, HTTPException
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/applications.py", line 16, in <module>
    from fastapi import routing
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/routing.py", line 22, in <module>
    from fastapi import params
  File "/data/software/anaconda3/lib/python3.9/site-packages/fastapi/params.py", line 5, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (/data/software/anaconda3/lib/python3.9/site-packages/pydantic/fields.py)

**Comment by RipperTs** [comment]
我认为错误的原因可能是 `Python` 的环境导致，最好的解决办法是新建一个`Python` 的虚拟环境。
然后使用参考的依赖版本：https://github.com/QwenLM/Qwen-7B/issues/191#issuecomment-1678721133

```
transformers==4.31.0
accelerate
tiktoken
einops
transformers_stream_generator==0.0.4
scipy
fastapi
uvicorn
openai
pydantic==2.1.1
sse_starlette
dashscope
```

**Comment by JustinLin610** [comment]
尽量更新版本到最新，包括openai

**Comment by 726663676** [comment]
本人pydantic的1.9.0版本也遇到这种情况，将版本升级到2.1.1问题得到解决
ubuntu20.04
tensorflow-gpu 2.9.0
openai 0.28.1
transformers-stream-generator 0.0.4
fastapi 0.103.2
accelerate 0.23.0

**Comment by 726663676** [comment]
本人pydantic的1.9.0版本也遇到这种情况，将版本升级到2.1.1问题得到解决
ubuntu20.04
tensorflow-gpu 2.9.0
openai 0.28.1
transformers-stream-generator 0.0.4
fastapi 0.103.2
accelerate 0.23.0
