### ISSUE TITLE
[BUG] 通过cli_demo.py方式运行72B模型正常，web_demo.py方式出现timeout问题

### ISSUE THREAD

**Issue by tanglu86** [QwenLM/Qwen-7B#721]
### 运行环境 | Environment

```Markdown
- OS:CentOS 7.7
- Python:Python 3.10.13
- Transformers:4.32.0
- PyTorch:2.1
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):21.1
- 服务器显存配置为4*A800，合计320G的显存
```

### 依赖环境安装方式
```
pip3 install -r requirements.txt
pip3 install -rrequirements_web_demo.txt
```

### 运行命令
```
python3 cli_demo.py  #正常推理
python3 web_demo.py  #出现超时
```

### 报错内容
通过cli_demo.py可以正常推理，通过web方式无法运行，出现了超时问题
![360截图20231204110224558](https://github.com/QwenLM/Qwen/assets/38269740/c7d0872c-a0ce-4dc5-afb6-e196ccc1cda8)

```
python3 web_demo.py 
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████| 82/82 [01:07<00:00,  1.22it/s]
Running on local URL:  http://127.0.0.1:8000
Traceback (most recent call last):
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
  File "/data/miniconda3/envs/qwen/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/data/miniconda3/envs/qwen/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/data/miniconda3/envs/qwen/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/data/miniconda3/envs/qwen/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='172.20.2.180', port=10809): Read timed out. (read timeout=3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/LLM_Project/Qwen/web_demo.py", line 209, in <module>
    main()
  File "/data/LLM_Project/Qwen/web_demo.py", line 205, in main
    _launch_demo(args, model, tokenizer, config)
  File "/data/LLM_Project/Qwen/web_demo.py", line 192, in _launch_demo
    demo.queue().launch(
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/gradio/blocks.py", line 1968, in launch
    and not networking.url_ok(self.local_url)
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/gradio/networking.py", line 202, in url_ok
    r = requests.head(url, timeout=3, verify=False)
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/data/miniconda3/envs/qwen/lib/python3.10/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='172.20.2.180', port=10809): Read timed out. (read timeout=3)
```

**Comment by tanglu86** [comment]
服务器代理问题
