### ISSUE TITLE
[BUG] windows 下 使用 modelscope 搭建环境有问题

### ISSUE THREAD

**Issue by dogvane** [QwenLM/Qwen-7B#82]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

安装方式：
conda create -n qwen python=3.10 -y

pip install modelscope
pip install -r requirements.txt

运行后无法执行，看结果应该是包有冲突，删除环境，删除pip的安装缓存，重新安装后结果也一样。

运行log：

2023-08-06 10:56:45,760 - modelscope - INFO - PyTorch version 2.0.1+cu118 Found.
2023-08-06 10:56:45,760 - modelscope - INFO - Loading ast index from C:\Users\dogvane\.cache\modelscope\ast_indexer
2023-08-06 10:56:46,154 - modelscope - INFO - Loading done! Current index file version is 1.8.1, with md5 6dce9f3d798398f7ff46f87d520c87f3 and a total number of 893 components indexed
2023-08-06 10:56:48,089 - modelscope - INFO - Model revision not specified, use the latest revision: v1.0.0
import flash_attn rotary fail
import flash_attn rms_norm fail
2023-08-06 10:56:49,708 - modelscope - INFO - initialize model from C:\Users\dogvane\.cache\modelscope\hub\qwen\Qwen-7B
C:\Users\dogvane\.conda\envs\qwen\lib\site-packages\torch\_utils.py:147: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the 
Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  t = torch.tensor([], dtype=storage.dtype, device=storage._untyped_storage.device)
2023-08-06 10:57:17,441 - modelscope - WARNING - No preprocessor field found in cfg.
2023-08-06 10:57:17,441 - modelscope - WARNING - No val key and type key found in preprocessor domain of configuration.json file.
2023-08-06 10:57:17,441 - modelscope - WARNING - Cannot find available config to build preprocessor at mode inference, current config: {'model_dir': 'C:\\Users\\dogvane\\.cache\\modelscope\\hub\\qwen\\Qwen-7B'}. trying to build by task and model information.
2023-08-06 10:57:17,441 - modelscope - WARNING - No preprocessor key ('qwen-7b', 'text-generation') found in PREPROCESSOR_MAP, skip building preprocessor.
Traceback (most recent call last):
  File "C:\ai\chatgpt\Qwen-7B\run.py", line 5, in <module>
    ret = p('翻译下文：hello world. my name is qwen.')
  File "C:\Users\dogvane\.conda\envs\qwen\lib\site-packages\modelscope\pipelines\base.py", line 219, in __call__
    output = self._process_single(input, *args, **kwargs)
  File "C:\Users\dogvane\.conda\envs\qwen\lib\site-packages\modelscope\pipelines\base.py", line 254, in _process_single
    out = self.forward(out, **forward_params)
  File "C:\Users\dogvane\.conda\envs\qwen\lib\site-packages\modelscope\pipelines\nlp\text_generation_pipeline.py", line 401, in forward
    self.model.chat(self.tokenizer, inputs,
  File "C:\Users\dogvane\.conda\envs\qwen\lib\site-packages\modelscope\models\nlp\qwen\text_generation.py", line 201, in chat
    response = decode_tokens(
  File "C:\Users\dogvane\.conda\envs\qwen\lib\site-packages\modelscope\models\nlp\qwen\qwen_generation_utils.py", line 259, in decode_tokens
    tokens = tokens.cpu().numpy().tolist()
RuntimeError: Numpy is not available

### 期望行为 | Expected Behavior

能正常运行

### 复现方法 | Steps To Reproduce

run.py

from modelscope.pipelines import pipeline
from modelscope.utils.constant import Tasks

p = pipeline('text-generation', 'qwen/Qwen-7B', device_map='auto')
ret = p('翻译下文：hello world. my name is qwen.')
print(ret)

### 运行环境 | Environment

```Markdown
- OS: win10
- Python: 3.10
- Transformers: 4.31.0
- PyTorch: 2.0.1
- CUDA: 11.8
```

**Comment by wenmengzhou** [comment]
RuntimeError: Numpy is not available   

pip install numpy

**Comment by dogvane** [comment]
解决了，是 modelscope 的问题。

conda 建立环境时，下的是 github代码，然后hf 连不上，又在相同环境下，用了 modelscope 的版本。
导致 modelscope 版本的numpy和github用的hf有冲突。

用hf的版本时，需要删除之前安装的 modelscope 包。
