### ISSUE TITLE
[BUG] <title>Using eos_token, but it is not set yet.   AttributeError: 'NoneType' object has no attribute 'join'

### ISSUE THREAD

**Issue by ArtificialZeng** [QwenLM/Qwen-7B#99]
### 是否已有关于该错误的issue？ | Is there an existing issue for this?

- [X] 我已经搜索过已有的issues | I have searched the existing issues

### 当前行为 | Current Behavior

  File "/home/zengzijian/ai_code/LLaMA-Efficient-Tuning/src/llmtuner/webui/chat.py", line 83, in predict
    for new_text in self.stream_chat(
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/home/zengzijian/ai_code/LLaMA-Efficient-Tuning/src/llmtuner/chat/stream_chat.py", line 91, in stream_chat
    gen_kwargs, _ = self.process_args(query, history, prefix, **input_kwargs)
  File "/home/zengzijian/ai_code/LLaMA-Efficient-Tuning/src/llmtuner/chat/stream_chat.py", line 33, in process_args
    prompt = self.template.get_prompt(query, history, prefix, self.tokenizer.eos_token)
  File "/home/zengzijian/ai_code/LLaMA-Efficient-Tuning/src/llmtuner/extras/template.py", line 24, in get_prompt
    return eos_token.join(map(lambda x: x[0] + x[1], self._format_example(query, history, prefix)))
AttributeError: 'NoneType' object has no attribute 'join'
Using eos_token, but it is not set yet.
Traceback (most recent call last):
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/gradio/routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/gradio/blocks.py", line 1392, in process_api
    result = await self.call_function(
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/gradio/blocks.py", line 1111, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/gradio/utils.py", line 346, in async_iteration
    return await iterator.__anext__()
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/gradio/utils.py", line 339, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/gradio/utils.py", line 322, in run_sync_iterator_async
    return next(iterator)
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/gradio/utils.py", line 691, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/home/zengzijian/ai_code/LLaMA-Efficient-Tuning/src/llmtuner/webui/chat.py", line 83, in predict
    for new_text in self.stream_chat(
  File "/home/zengzijian/miniconda3/envs/py10_backup/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 43, in generator_context
    response = gen.send(None)
  File "/home/zengzijian/ai_code/LLaMA-Efficient-Tuning/src/llmtuner/chat/stream_chat.py", line 91, in stream_chat
    gen_kwargs, _ = self.process_args(query, history, prefix, **input_kwargs)
  File "/home/zengzijian/ai_code/LLaMA-Efficient-Tuning/src/llmtuner/chat/stream_chat.py", line 33, in process_args
    prompt = self.template.get_prompt(query, history, prefix, self.tokenizer.eos_token)
  File "/home/zengzijian/ai_code/LLaMA-Efficient-Tuning/src/llmtuner/extras/template.py", line 24, in get_prompt
    return eos_token.join(map(lambda x: x[0] + x[1], self._format_example(query, history, prefix)))
AttributeError: 'NoneType' object has no attribute 'join'

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by jklj077** [comment]
It seems this issue has been fixed in the newest version of LLaMA-Efficient-Tuning. Please update the package to see if this issue still exists.

Downstream issue: https://github.com/hiyouga/LLaMA-Efficient-Tuning/issues/385

General note: Now, special tokens can be added to QwenTokenizer when initialized by simply passing `<...>_token="..."`. But please do check the meaning of the special tokens are used consistently.

**Comment by jklj077** [comment]
close as resolved; please reopen this if the problem exists; thank you for your feedback!
